In [4]:
import numpy as np
import pandas as pd
df=pd.read_csv("D:/Data Analysis/adm_data.csv")
df

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65
...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
398,399,312,103,3,3.5,4.0,8.78,0,0.67
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [6]:
df.shape

(400, 9)

In [8]:
df.size

3600

In [11]:
df.describe()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,200.500000,316.807500,107.410000,3.087500,3.400000,3.452500,8.598925,0.547500,0.724350
std,115.614301,11.473646,6.069514,1.143728,1.006869,0.898478,0.596317,0.498362,0.142609
min,1.000000,290.000000,92.000000,1.000000,1.000000,1.000000,6.800000,0.000000,0.340000
25%,100.750000,308.000000,103.000000,2.000000,2.500000,3.000000,8.170000,0.000000,0.640000
50%,200.500000,317.000000,107.000000,3.000000,3.500000,3.500000,8.610000,1.000000,0.730000
75%,300.250000,325.000000,112.000000,4.000000,4.000000,4.000000,9.062500,1.000000,0.830000
max,400.000000,340.000000,120.000000,5.000000,5.000000,5.000000,9.920000,1.000000,0.970000

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Serial No.         400 non-null    int64
 1   GRE Score          400 non-null    int64
 2   TOEFL Score        400 non-null    int64
 3   University Rating  400 non-null    int64
 4   SOP                400 non-null    float64
 5   LOR                400 non-null    float64
 6   CGPA               400 non-null    float64
 7   Research           400 non-null    int64
 8   Chance of Admit    400 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 28.2 KB

In [15]:
df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [16]:
df.tail()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
398,399,312,103,3,3.5,4.0,8.78,0,0.67
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [13]:
df.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [18]:
df.isna().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [22]:
x=df.iloc[:,:-1].values  #input data cols
x

array([[  1.  , 337.  , 118.  , ...,   4.5 ,   9.65,   1.  ],
       [  2.  , 324.  , 107.  , ...,   4.5 ,   8.87,   1.  ],
       [  3.  , 316.  , 104.  , ...,   3.5 ,   8.  ,   1.  ],
       ...,
       [398.  , 330.  , 116.  , ...,   4.5 ,   9.45,   1.  ],
       [399.  , 312.  , 103.  , ...,   4.  ,   8.78,   0.  ],
       [400.  , 333.  , 117.  , ...,   4.  ,   9.66,   1.  ]])

In [25]:
y=df.iloc[:,-1].values #outputdata cols
y

array([0.92, 0.76, 0.72, 0.8 , 0.65, 0.9 , 0.75, 0.68, 0.5 , 0.45, 0.52,
       0.84, 0.78, 0.62, 0.61, 0.54, 0.66, 0.65, 0.63, 0.62, 0.64, 0.7 ,
       0.94, 0.95, 0.97, 0.94, 0.76, 0.44, 0.46, 0.54, 0.65, 0.74, 0.91,
       0.9 , 0.94, 0.88, 0.64, 0.58, 0.52, 0.48, 0.46, 0.49, 0.53, 0.87,
       0.91, 0.88, 0.86, 0.89, 0.82, 0.78, 0.76, 0.56, 0.78, 0.72, 0.7 ,
       0.64, 0.64, 0.46, 0.36, 0.42, 0.48, 0.47, 0.54, 0.56, 0.52, 0.55,
       0.61, 0.57, 0.68, 0.78, 0.94, 0.96, 0.93, 0.84, 0.74, 0.72, 0.74,
       0.64, 0.44, 0.46, 0.5 , 0.96, 0.92, 0.92, 0.94, 0.76, 0.72, 0.66,
       0.64, 0.74, 0.64, 0.38, 0.34, 0.44, 0.36, 0.42, 0.48, 0.86, 0.9 ,
       0.79, 0.71, 0.64, 0.62, 0.57, 0.74, 0.69, 0.87, 0.91, 0.93, 0.68,
       0.61, 0.69, 0.62, 0.72, 0.59, 0.66, 0.56, 0.45, 0.47, 0.71, 0.94,
       0.94, 0.57, 0.61, 0.57, 0.64, 0.85, 0.78, 0.84, 0.92, 0.96, 0.77,
       0.71, 0.79, 0.89, 0.82, 0.76, 0.71, 0.8 , 0.78, 0.84, 0.9 , 0.92,
       0.97, 0.8 , 0.81, 0.75, 0.83, 0.96, 0.79, 0.93, 0.94, 0.86, 0.79,
       0.8 , 0.77, 0.7 , 0.65, 0.61, 0.52, 0.57, 0.53, 0.67, 0.68, 0.81,
       0.78, 0.65, 0.64, 0.64, 0.65, 0.68, 0.89, 0.86, 0.89, 0.87, 0.85,
       0.9 , 0.82, 0.72, 0.73, 0.71, 0.71, 0.68, 0.75, 0.72, 0.89, 0.84,
       0.93, 0.93, 0.88, 0.9 , 0.87, 0.86, 0.94, 0.77, 0.78, 0.73, 0.73,
       0.7 , 0.72, 0.73, 0.72, 0.97, 0.97, 0.69, 0.57, 0.63, 0.66, 0.64,
       0.68, 0.79, 0.82, 0.95, 0.96, 0.94, 0.93, 0.91, 0.85, 0.84, 0.74,
       0.76, 0.75, 0.76, 0.71, 0.67, 0.61, 0.63, 0.64, 0.71, 0.82, 0.73,
       0.74, 0.69, 0.64, 0.91, 0.88, 0.85, 0.86, 0.7 , 0.59, 0.6 , 0.65,
       0.7 , 0.76, 0.63, 0.81, 0.72, 0.71, 0.8 , 0.77, 0.74, 0.7 , 0.71,
       0.93, 0.85, 0.79, 0.76, 0.78, 0.77, 0.9 , 0.87, 0.71, 0.7 , 0.7 ,
       0.75, 0.71, 0.72, 0.73, 0.83, 0.77, 0.72, 0.54, 0.49, 0.52, 0.58,
       0.78, 0.89, 0.7 , 0.66, 0.67, 0.68, 0.8 , 0.81, 0.8 , 0.94, 0.93,
       0.92, 0.89, 0.82, 0.79, 0.58, 0.56, 0.56, 0.64, 0.61, 0.68, 0.76,
       0.86, 0.9 , 0.71, 0.62, 0.66, 0.65, 0.73, 0.62, 0.74, 0.79, 0.8 ,
       0.69, 0.7 , 0.76, 0.84, 0.78, 0.67, 0.66, 0.65, 0.54, 0.58, 0.79,
       0.8 , 0.75, 0.73, 0.72, 0.62, 0.67, 0.81, 0.63, 0.69, 0.8 , 0.43,
       0.8 , 0.73, 0.75, 0.71, 0.73, 0.83, 0.72, 0.94, 0.81, 0.81, 0.75,
       0.79, 0.58, 0.59, 0.47, 0.49, 0.47, 0.42, 0.57, 0.62, 0.74, 0.73,
       0.64, 0.63, 0.59, 0.73, 0.79, 0.68, 0.7 , 0.81, 0.85, 0.93, 0.91,
       0.69, 0.77, 0.86, 0.74, 0.57, 0.51, 0.67, 0.72, 0.89, 0.95, 0.79,
       0.39, 0.38, 0.34, 0.47, 0.56, 0.71, 0.78, 0.73, 0.82, 0.62, 0.96,
       0.96, 0.46, 0.53, 0.49, 0.76, 0.64, 0.71, 0.84, 0.77, 0.89, 0.82,
       0.84, 0.91, 0.67, 0.95])

In [31]:
#Set as Training data and Testing data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30)
y_test

array([0.49, 0.66, 0.93, 0.83, 0.7 , 0.84, 0.77, 0.95, 0.51, 0.54, 0.96,
       0.94, 0.87, 0.73, 0.71, 0.94, 0.84, 0.8 , 0.68, 0.47, 0.64, 0.78,
       0.77, 0.64, 0.68, 0.62, 0.72, 0.73, 0.71, 0.74, 0.77, 0.9 , 0.64,
       0.94, 0.77, 0.73, 0.81, 0.57, 0.85, 0.79, 0.54, 0.65, 0.75, 0.68,
       0.64, 0.56, 0.71, 0.82, 0.53, 0.8 , 0.86, 0.64, 0.89, 0.7 , 0.9 ,
       0.52, 0.58, 0.75, 0.73, 0.8 , 0.8 , 0.45, 0.69, 0.92, 0.63, 0.97,
       0.89, 0.42, 0.76, 0.71, 0.79, 0.85, 0.53, 0.79, 0.84, 0.9 , 0.66,
       0.8 , 0.78, 0.86, 0.94, 0.94, 0.93, 0.75, 0.79, 0.76, 0.74, 0.64,
       0.83, 0.91, 0.74, 0.46, 0.8 , 0.93, 0.85, 0.78, 0.87, 0.71, 0.82,
       0.58, 0.54, 0.73, 0.69, 0.68, 0.66, 0.72, 0.61, 0.5 , 0.74, 0.63,
       0.91, 0.72, 0.74, 0.71, 0.89, 0.85, 0.95, 0.93, 0.52, 0.72])

In [33]:
#Normalization ---->standardscaler--(values are cahnged to similar values else higher value be evaluated)
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_test

array([[ 1.30548423e+00,  1.78233074e-02, -1.49458839e+00,
        -1.82490912e+00, -1.89494656e+00, -1.60591320e+00,
        -1.88156818e+00, -1.02899151e+00],
       [-6.90650072e-01, -4.98438011e-01, -1.64481916e-01,
         7.60122349e-01,  1.07197816e+00,  1.15609967e+00,
         7.82243565e-01,  9.71825316e-01],
       [ 1.44434575e+00,  1.56660726e+00,  1.49815117e+00,
         7.60122349e-01,  5.77490704e-01,  5.12945248e-02,
         1.60951429e+00,  9.71825316e-01],
       [ 6.37213184e-01,  9.64302390e-01,  9.99361246e-01,
         7.60122349e-01,  1.07197816e+00,  1.70850225e+00,
         9.47697711e-01, -1.02899151e+00],
       [-1.50646148e+00,  7.92215284e-01,  1.16562455e+00,
         7.60122349e-01, -4.11484202e-01, -1.60591320e+00,
        -2.76662968e-01, -1.02899151e+00],
       [-7.44520901e-02,  1.03866860e-01,  1.78139259e-03,
        -1.01554808e-01,  8.30032511e-02, -5.01108050e-01,
         1.86608640e-01,  9.71825316e-01],
       [ 5.50424736e-01,  8.78258837e-01, -8.29535152e-01,
         7.60122349e-01,  1.56646561e+00,  1.70850225e+00,
         3.18971957e-01,  9.71825316e-01],
       [ 1.53981304e+00,  1.73869437e+00,  1.99694110e+00,
         7.60122349e-01,  1.07197816e+00,  6.03697099e-01,
         1.74187761e+00,  9.71825316e-01],
       [ 1.50509767e+00, -1.53096065e+00, -2.49216824e+00,
        -1.82490912e+00, -1.40045911e+00, -1.60591320e+00,
        -1.13702453e+00, -1.02899151e+00],
       [ 6.63249719e-01, -1.44491709e+00, -1.82711500e+00,
        -9.63231965e-01, -1.89494656e+00, -1.60591320e+00,
        -1.17011536e+00, -1.02899151e+00],
       [ 1.65263803e+00,  1.65265081e+00,  1.66441448e+00,
         1.62179951e+00,  1.56646561e+00,  1.70850225e+00,
         2.07278590e+00,  9.71825316e-01],
       [-1.47174610e+00,  2.08286858e+00,  2.16320441e+00,
         1.62179951e+00,  1.07197816e+00,  1.15609967e+00,
         1.70878678e+00,  9.71825316e-01],
       [-1.78598228e-01,  4.48041072e-01,  6.66834628e-01,
         7.60122349e-01,  5.77490704e-01,  6.03697099e-01,
         6.66425663e-01,  9.71825316e-01],
       [ 1.21001694e+00, -3.26350905e-01,  1.78139259e-03,
         7.60122349e-01,  1.07197816e+00,  6.03697099e-01,
         1.36972396e-01,  9.71825316e-01],
       [ 4.54957443e-01, -4.12394458e-01, -4.97008534e-01,
        -9.63231965e-01, -9.05971655e-01,  5.12945248e-02,
        -1.44299651e-01, -1.02899151e+00],
       [-6.38577003e-01,  1.56660726e+00,  1.99694110e+00,
         1.62179951e+00,  1.07197816e+00,  1.15609967e+00,
         1.51024181e+00,  9.71825316e-01],
       [-1.59324993e+00,  9.64302390e-01,  6.66834628e-01,
         7.60122349e-01,  5.77490704e-01,  1.15609967e+00,
         7.16061907e-01,  9.71825316e-01],
       [-3.52175124e-01,  8.78258837e-01,  1.68044701e-01,
        -1.01554808e-01, -4.11484202e-01,  5.12945248e-02,
         5.34062346e-01, -1.02899151e+00],
       [ 8.71541994e-01,  1.03866860e-01, -1.16206177e+00,
        -9.63231965e-01, -4.11484202e-01, -1.05351062e+00,
         4.60907978e-03, -1.02899151e+00],
       [ 1.58320727e+00, -2.21930907e+00, -1.16206177e+00,
        -1.82490912e+00, -1.89494656e+00, -1.60591320e+00,
        -1.66647779e+00, -1.02899151e+00],
       [-1.21138076e+00,  3.61997519e-01, -6.63271843e-01,
        -1.01554808e-01, -4.11484202e-01, -5.01108050e-01,
        -1.43484199e+00, -1.02899151e+00],
       [ 6.97965098e-01,  5.34084625e-01,  5.00571319e-01,
        -1.01554808e-01,  8.30032511e-02, -5.01108050e-01,
         6.49880249e-01,  9.71825316e-01],
       [-5.02133164e-03,  1.78233074e-02,  3.34308010e-01,
        -1.01554808e-01,  8.30032511e-02, -5.01108050e-01,
         3.18971957e-01, -1.02899151e+00],
       [-8.12153899e-01, -3.26350905e-01, -3.30745225e-01,
        -9.63231965e-01, -9.05971655e-01, -5.01108050e-01,
        -7.39934576e-01, -1.02899151e+00],
       [ 7.41359322e-01, -4.12394458e-01, -8.29535152e-01,
        -1.01554808e-01,  1.07197816e+00,  6.03697099e-01,
         1.20426982e-01,  9.71825316e-01],
       [ 9.49651598e-01, -2.40307352e-01, -1.64481916e-01,
        -9.63231965e-01, -9.05971655e-01, -1.60591320e+00,
        -2.27026724e-01, -1.02899151e+00],
       [ 1.52245536e+00, -4.98438011e-01, -6.63271843e-01,
        -9.63231965e-01, -9.05971655e-01, -1.05351062e+00,
        -5.41389601e-01, -1.02899151e+00],
       [-1.35204004e-01, -7.56568670e-01, -8.29535152e-01,
        -1.01554808e-01, -4.11484202e-01, -5.01108050e-01,
        -4.91753358e-01, -1.02899151e+00],
       [-4.99715486e-01,  1.78233074e-02, -1.16206177e+00,
        -9.63231965e-01, -1.89494656e+00, -5.01108050e-01,
        -6.73752918e-01,  9.71825316e-01],
       [ 9.58330442e-01,  4.48041072e-01,  3.34308010e-01,
        -1.01554808e-01,  8.30032511e-02,  5.12945248e-02,
         3.85153615e-01,  9.71825316e-01],
       [ 4.72315133e-01,  4.48041072e-01,  6.66834628e-01,
        -1.01554808e-01,  8.30032511e-02,  6.03697099e-01,
         4.34789859e-01,  9.71825316e-01],
       [-1.61240538e-01,  1.13638950e+00,  1.99694110e+00,
         7.60122349e-01,  1.07197816e+00,  1.15609967e+00,
         9.80788540e-01,  9.71825316e-01],
       [-2.30671297e-01, -1.96117841e+00, -1.66085170e+00,
        -9.63231965e-01, -1.40045911e+00,  6.03697099e-01,
        -1.26938784e+00,  9.71825316e-01],
       [-9.59694261e-01,  2.08286858e+00,  1.33188786e+00,
         1.62179951e+00,  1.07197816e+00,  1.15609967e+00,
         1.46060556e+00,  9.71825316e-01],
       [ 1.72206879e+00,  1.03866860e-01, -4.97008534e-01,
        -9.63231965e-01, -4.11484202e-01, -5.01108050e-01,
         3.18971957e-01, -1.02899151e+00],
       [ 1.39227268e+00,  1.03866860e-01, -1.64481916e-01,
        -9.63231965e-01, -1.40045911e+00,  5.12945248e-02,
        -7.39934576e-01, -1.02899151e+00],
       [-4.30284727e-01,  3.61997519e-01,  9.99361246e-01,
        -9.63231965e-01, -1.40045911e+00, -1.05351062e+00,
         1.20426982e-01,  9.71825316e-01],
       [ 1.49641882e+00, -4.12394458e-01, -1.49458839e+00,
        -1.82490912e+00, -2.38943401e+00, -1.05351062e+00,
        -1.83193194e+00, -1.02899151e+00],
       [ 1.94592099e-01,  4.48041072e-01,  3.34308010e-01,
         7.60122349e-01,  5.77490704e-01,  6.03697099e-01,
         9.31152296e-01,  9.71825316e-01],
       [-5.34430865e-01,  6.20128178e-01,  8.33097937e-01,
         1.62179951e+00,  5.77490704e-01,  1.15609967e+00,
         3.52062786e-01, -1.02899151e+00],
       [-1.15062885e+00, -1.01469933e+00, -3.30745225e-01,
        -9.63231965e-01, -4.11484202e-01, -5.01108050e-01,
        -6.07571260e-01,  9.71825316e-01],
       [ 4.02884375e-01,  1.03866860e-01, -6.63271843e-01,
        -9.63231965e-01, -9.05971655e-01, -1.60591320e+00,
        -6.90298333e-01, -1.02899151e+00],
       [ 6.02497805e-01,  7.92215284e-01,  5.00571319e-01,
        -9.63231965e-01, -4.11484202e-01, -1.05351062e+00,
         3.18971957e-01,  9.71825316e-01],
       [-2.13313607e-01, -3.26350905e-01, -9.95798460e-01,
        -9.63231965e-01, -9.05971655e-01,  5.12945248e-02,
        -8.72297893e-01,  9.71825316e-01],
       [ 8.54184305e-01, -3.26350905e-01, -1.49458839e+00,
        -1.82490912e+00,  8.30032511e-02, -5.01108050e-01,
        -6.40662089e-01,  9.71825316e-01],
       [-1.14195000e+00, -6.82202456e-02,  1.78139259e-03,
        -9.63231965e-01,  5.77490704e-01, -5.01108050e-01,
        -1.11208822e-01,  9.71825316e-01],
       [ 1.70471110e+00,  1.89910413e-01, -1.64481916e-01,
        -1.01554808e-01, -1.40045911e+00, -5.01108050e-01,
         1.36972396e-01, -1.02899151e+00],
       [ 2.98738237e-01,  7.06171731e-01,  6.66834628e-01,
         7.60122349e-01, -4.11484202e-01, -5.01108050e-01,
         7.32607321e-01,  9.71825316e-01],
       [-1.32420574e+00, -2.40307352e-01,  1.78139259e-03,
        -9.63231965e-01, -9.05971655e-01, -1.60591320e+00,
        -1.11208822e-01,  9.71825316e-01],
       [-1.66268069e+00,  5.34084625e-01,  5.00571319e-01,
        -1.01554808e-01,  8.30032511e-02, -1.05351062e+00,
         1.70063226e-01,  9.71825316e-01],
       [-1.28949036e+00,  1.13638950e+00,  1.16562455e+00,
         1.62179951e+00,  5.77490704e-01,  1.70850225e+00,
         1.21242434e+00,  9.71825316e-01],
       [-9.07621192e-01,  1.89910413e-01, -1.64481916e-01,
        -9.63231965e-01,  5.77490704e-01,  6.03697099e-01,
        -1.07084287e+00,  9.71825316e-01],
       [ 1.73074763e+00,  1.13638950e+00,  6.66834628e-01,
         7.60122349e-01,  1.07197816e+00,  6.03697099e-01,
         1.09660644e+00,  9.71825316e-01],
       [ 3.76847840e-01, -4.98438011e-01, -4.97008534e-01,
        -1.01554808e-01, -1.40045911e+00,  5.12945248e-02,
        -3.26299212e-01, -1.02899151e+00],
       [ 5.59103581e-01,  1.30847660e+00,  1.99694110e+00,
         7.60122349e-01,  1.56646561e+00,  1.15609967e+00,
         1.27860600e+00,  9.71825316e-01],
       [-1.13327116e+00,  7.92215284e-01,  6.66834628e-01,
        -1.01554808e-01, -4.11484202e-01,  5.12945248e-02,
         2.19699469e-01, -1.02899151e+00],
       [ 6.89286253e-01, -6.82202456e-02, -1.16206177e+00,
        -1.82490912e+00, -1.40045911e+00, -1.05351062e+00,
        -1.02120662e+00, -1.02899151e+00],
       [-4.21605883e-01, -6.82202456e-02, -3.30745225e-01,
        -1.01554808e-01, -1.40045911e+00, -1.05351062e+00,
        -1.44299651e-01, -1.02899151e+00],
       [ 1.61792265e+00,  2.75953966e-01, -3.30745225e-01,
        -1.01554808e-01, -4.11484202e-01,  5.12945248e-02,
         1.70063226e-01,  9.71825316e-01],
       [ 1.17530156e+00,  9.64302390e-01,  9.99361246e-01,
        -1.01554808e-01,  8.30032511e-02, -5.01108050e-01,
         1.53517811e-01,  9.71825316e-01],
       [ 7.67395857e-01,  4.48041072e-01,  6.66834628e-01,
        -1.01554808e-01, -9.05971655e-01, -5.01108050e-01,
         5.50607761e-01,  9.71825316e-01],
       [-6.73292382e-01, -2.21930907e+00, -4.97008534e-01,
         7.60122349e-01, -1.40045911e+00, -1.05351062e+00,
        -1.83193194e+00, -1.02899151e+00],
       [-7.77438520e-01,  1.78233074e-02,  5.00571319e-01,
        -1.01554808e-01,  5.77490704e-01,  1.15609967e+00,
         3.52062786e-01,  9.71825316e-01],
       [-4.56321262e-01,  1.30847660e+00,  1.33188786e+00,
         1.62179951e+00,  5.77490704e-01,  5.12945248e-02,
         1.44406015e+00,  9.71825316e-01],
       [-1.53249802e+00,  1.89910413e-01,  5.00571319e-01,
        -1.01554808e-01,  5.77490704e-01, -5.01108050e-01,
         3.85153615e-01, -1.02899151e+00],
       [-4.47642417e-01,  2.08286858e+00,  2.16320441e+00,
         7.60122349e-01,  1.07197816e+00,  6.03697099e-01,
         2.23824005e+00,  9.71825316e-01],
       [ 1.53113420e+00,  7.06171731e-01,  5.00571319e-01,
        -1.01554808e-01,  8.30032511e-02, -5.01108050e-01,
         1.08006103e+00,  9.71825316e-01],
       [-8.64226968e-01, -1.01469933e+00, -1.16206177e+00,
         7.60122349e-01, -1.89494656e+00, -1.05351062e+00,
        -1.20320618e+00, -1.02899151e+00],
       [-1.68003838e+00,  7.06171731e-01,  1.78139259e-03,
         7.60122349e-01,  5.77490704e-01,  1.15609967e+00,
         5.00971517e-01,  9.71825316e-01],
       [ 2.90059392e-01,  1.89910413e-01,  8.33097937e-01,
        -1.01554808e-01,  5.77490704e-01,  5.12945248e-02,
         1.70063226e-01, -1.02899151e+00],
       [ 9.67009287e-01,  6.20128178e-01,  5.00571319e-01,
        -1.01554808e-01,  5.77490704e-01,  5.12945248e-02,
         8.81516053e-01,  9.71825316e-01],
       [ 1.43566691e+00,  5.34084625e-01,  5.00571319e-01,
        -1.01554808e-01,  5.77490704e-01,  1.70850225e+00,
         1.20426982e-01,  9.71825316e-01],
       [ 1.66999572e+00, -7.56568670e-01, -3.30745225e-01,
        -9.63231965e-01, -1.40045911e+00,  5.12945248e-02,
        -7.73025406e-01, -1.02899151e+00],
       [ 1.27076886e+00,  8.78258837e-01,  5.00571319e-01,
        -1.01554808e-01,  8.30032511e-02,  5.12945248e-02,
         3.18971957e-01,  9.71825316e-01],
       [-5.77825089e-01,  8.78258837e-01,  8.33097937e-01,
        -1.01554808e-01,  8.30032511e-02, -5.01108050e-01,
         8.81516053e-01,  9.71825316e-01],
       [-8.38190434e-01,  1.39452016e+00,  1.99694110e+00,
         7.60122349e-01,  1.56646561e+00,  1.15609967e+00,
         1.11315186e+00,  9.71825316e-01],
       [ 9.23615063e-01,  2.75953966e-01,  1.68044701e-01,
        -9.63231965e-01, -9.05971655e-01, -5.01108050e-01,
         3.18971957e-01, -1.02899151e+00],
       [-4.91036641e-01,  8.78258837e-01,  1.49815117e+00,
        -9.63231965e-01,  1.07197816e+00, -5.01108050e-01,
         8.48425224e-01,  9.71825316e-01],
       [-5.86503934e-01,  2.75953966e-01,  8.33097937e-01,
        -1.01554808e-01, -9.05971655e-01, -1.60591320e+00,
         2.36244884e-01,  9.71825316e-01],
       [-8.46869278e-01,  1.30847660e+00,  2.16320441e+00,
        -1.01554808e-01,  5.77490704e-01,  6.03697099e-01,
         6.49880249e-01,  9.71825316e-01],
       [-6.47255848e-01,  1.65265081e+00,  1.66441448e+00,
         1.62179951e+00,  1.56646561e+00,  1.70850225e+00,
         1.64260512e+00,  9.71825316e-01],
       [-1.39363650e+00,  1.30847660e+00,  8.33097937e-01,
         1.62179951e+00,  5.77490704e-01,  1.70850225e+00,
         2.03969507e+00,  9.71825316e-01],
       [-3.86890503e-01,  1.56660726e+00,  1.16562455e+00,
         7.60122349e-01,  5.77490704e-01,  6.03697099e-01,
         1.42751473e+00,  9.71825316e-01],
       [ 1.08851311e+00,  1.03866860e-01, -1.64481916e-01,
        -1.01554808e-01,  5.77490704e-01,  5.12945248e-02,
        -1.11208822e-01,  9.71825316e-01],
       [ 8.19468925e-01, -2.40307352e-01,  3.34308010e-01,
        -1.01554808e-01,  5.77490704e-01,  5.12945248e-02,
         7.16061907e-01, -1.02899151e+00],
       [ 1.68735341e+00,  3.61997519e-01,  1.68044701e-01,
        -1.01554808e-01,  8.30032511e-02,  6.03697099e-01,
        -2.10481310e-01,  9.71825316e-01],
       [ 4.80993978e-01,  3.61997519e-01, -4.97008534e-01,
        -1.01554808e-01, -4.11484202e-01, -1.05351062e+00,
         4.60907978e-03,  9.71825316e-01],
       [ 1.16482496e-01, -9.28655776e-01, -1.64481916e-01,
        -9.63231965e-01, -4.11484202e-01, -5.01108050e-01,
        -6.73752918e-01, -1.02899151e+00],
       [-4.12927038e-01,  8.78258837e-01,  1.16562455e+00,
        -1.01554808e-01, -4.11484202e-01, -5.01108050e-01,
         8.98061467e-01,  9.71825316e-01],
       [ 1.45302460e+00,  1.91078147e+00,  1.33188786e+00,
         1.62179951e+00,  1.07197816e+00,  1.70850225e+00,
         1.09660644e+00,  9.71825316e-01],
       [ 2.11949789e-01, -3.26350905e-01, -4.97008534e-01,
        -1.01554808e-01,  8.30032511e-02,  5.12945248e-02,
        -2.43572139e-01, -1.02899151e+00],
       [-1.44570957e+00, -1.78909131e+00, -2.32590493e+00,
        -1.82490912e+00, -1.40045911e+00, -1.60591320e+00,
        -2.26211272e+00, -1.02899151e+00],
       [ 1.07983427e+00,  9.64302390e-01,  9.99361246e-01,
         7.60122349e-01,  8.30032511e-02, -5.01108050e-01,
         2.03154055e-01,  9.71825316e-01],
       [ 5.07030512e-01,  1.65265081e+00,  1.33188786e+00,
         7.60122349e-01,  1.07197816e+00,  1.15609967e+00,
         1.84115010e+00,  9.71825316e-01],
       [ 3.59490150e-01,  7.92215284e-01,  8.33097937e-01,
         7.60122349e-01,  5.77490704e-01,  1.15609967e+00,
         9.97333955e-01,  9.71825316e-01],
       [-4.82357796e-01,  1.89910413e-01,  3.34308010e-01,
        -1.82490912e+00,  8.30032511e-02,  5.12945248e-02,
         9.14606882e-01, -1.02899151e+00],
       [-7.68759675e-01,  1.13638950e+00,  6.66834628e-01,
         7.60122349e-01,  1.07197816e+00,  1.15609967e+00,
         1.01387937e+00,  9.71825316e-01],
       [-1.17846314e-01, -9.28655776e-01,  1.78139259e-03,
        -9.63231965e-01, -9.05971655e-01, -1.05351062e+00,
        -2.43572139e-01, -1.02899151e+00],
       [ 1.73942648e+00,  7.06171731e-01,  5.00571319e-01,
        -1.01554808e-01,  8.30032511e-02,  5.12945248e-02,
         7.82243565e-01,  9.71825316e-01],
       [ 8.28147770e-01, -7.56568670e-01, -3.30745225e-01,
        -9.63231965e-01, -9.05971655e-01, -5.01108050e-01,
        -1.51756906e+00, -1.02899151e+00],
       [-1.55853455e+00, -1.54263799e-01, -3.30745225e-01,
        -1.01554808e-01,  8.30032511e-02, -1.05351062e+00,
        -4.42117114e-01, -1.02899151e+00],
       [ 1.18398041e+00, -4.12394458e-01, -3.30745225e-01,
        -9.63231965e-01, -4.11484202e-01, -1.60591320e+00,
        -7.39934576e-01,  9.71825316e-01],
       [ 3.24774771e-01, -3.26350905e-01,  1.78139259e-03,
        -9.63231965e-01, -9.05971655e-01,  5.12945248e-02,
        -4.91753358e-01, -1.02899151e+00],
       [ 1.25161341e-01, -1.27282999e+00, -4.97008534e-01,
        -1.01554808e-01,  8.30032511e-02,  6.03697099e-01,
        -7.39934576e-01,  9.71825316e-01],
       [ 1.03644005e+00, -9.28655776e-01, -3.30745225e-01,
        -9.63231965e-01, -4.11484202e-01,  6.03697099e-01,
        -7.23389162e-01, -1.02899151e+00],
       [-7.08007761e-01,  3.61997519e-01,  5.00571319e-01,
        -9.63231965e-01,  5.77490704e-01,  5.12945248e-02,
        -1.19363348e-02, -1.02899151e+00],
       [-6.21219313e-01, -6.70525117e-01,  1.68044701e-01,
        -1.01554808e-01,  8.30032511e-02,  5.12945248e-02,
        -5.74480431e-01, -1.02899151e+00],
       [-9.94409640e-01, -3.26350905e-01, -3.30745225e-01,
        -1.01554808e-01, -1.40045911e+00, -5.01108050e-01,
        -9.05388722e-01,  9.71825316e-01],
       [ 1.48773998e+00,  3.61997519e-01, -4.97008534e-01,
        -1.01554808e-01,  8.30032511e-02,  1.15609967e+00,
        -3.75935456e-01,  9.71825316e-01],
       [ 1.37491499e+00, -1.35887354e+00, -8.29535152e-01,
        -1.01554808e-01,  8.30032511e-02, -1.05351062e+00,
        -6.57207504e-01, -1.02899151e+00],
       [-7.60080830e-01,  1.91078147e+00,  1.66441448e+00,
         7.60122349e-01,  8.30032511e-02,  1.15609967e+00,
         1.47715098e+00,  9.71825316e-01],
       [-1.03780386e+00,  1.13638950e+00,  1.16562455e+00,
        -9.63231965e-01, -1.40045911e+00,  6.03697099e-01,
        -1.19363348e-02,  9.71825316e-01],
       [-7.86117365e-01,  8.78258837e-01,  8.33097937e-01,
        -1.01554808e-01,  8.30032511e-02, -5.01108050e-01,
         7.98788980e-01,  9.71825316e-01],
       [ 1.60056496e+00, -4.12394458e-01, -1.32832508e+00,
        -1.82490912e+00, -9.05971655e-01, -5.01108050e-01,
        -2.27026724e-01,  9.71825316e-01],
       [ 8.02111236e-01,  7.06171731e-01,  1.16562455e+00,
         1.62179951e+00,  1.56646561e+00,  1.15609967e+00,
         8.48425224e-01,  9.71825316e-01],
       [-1.69919383e-01,  3.61997519e-01,  6.66834628e-01,
         7.60122349e-01,  1.07197816e+00,  5.12945248e-02,
         5.00971517e-01,  9.71825316e-01],
       [ 1.51197875e-01,  1.91078147e+00,  2.16320441e+00,
         7.60122349e-01,  1.56646561e+00,  1.70850225e+00,
         1.80805927e+00,  9.71825316e-01],
       [-7.51401985e-01,  1.30847660e+00,  1.49815117e+00,
         1.62179951e+00,  1.56646561e+00,  1.70850225e+00,
         1.34478766e+00,  9.71825316e-01],
       [ 6.80607408e-01, -3.26350905e-01, -1.32832508e+00,
        -1.82490912e+00, -2.38943401e+00, -2.15831577e+00,
        -9.21934137e-01,  9.71825316e-01],
       [-9.42336571e-01, -6.82202456e-02, -1.64481916e-01,
        -1.01554808e-01,  1.07197816e+00,  5.12945248e-02,
        -2.43572139e-01, -1.02899151e+00]])

In [35]:
#Training Model
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [37]:
y_pred=np.round(model.predict(x_test),2)
y_pred

array([0.52, 0.79, 0.93, 0.86, 0.67, 0.73, 0.8 , 0.97, 0.51, 0.53, 1.01,
       0.94, 0.81, 0.77, 0.67, 0.93, 0.81, 0.75, 0.65, 0.51, 0.57, 0.79,
       0.72, 0.61, 0.73, 0.65, 0.64, 0.62, 0.63, 0.79, 0.8 , 0.89, 0.58,
       0.92, 0.72, 0.67, 0.73, 0.53, 0.83, 0.79, 0.62, 0.6 , 0.75, 0.63,
       0.63, 0.68, 0.73, 0.81, 0.65, 0.71, 0.89, 0.65, 0.88, 0.67, 0.92,
       0.73, 0.58, 0.65, 0.76, 0.79, 0.79, 0.52, 0.77, 0.89, 0.7 , 0.97,
       0.83, 0.55, 0.78, 0.74, 0.82, 0.82, 0.65, 0.8 , 0.8 , 0.89, 0.73,
       0.8 , 0.72, 0.84, 0.95, 0.93, 0.89, 0.74, 0.76, 0.77, 0.71, 0.62,
       0.81, 0.95, 0.67, 0.39, 0.8 , 0.95, 0.87, 0.74, 0.85, 0.64, 0.83,
       0.58, 0.61, 0.64, 0.66, 0.66, 0.65, 0.7 , 0.65, 0.63, 0.75, 0.62,
       0.92, 0.76, 0.79, 0.67, 0.88, 0.79, 0.98, 0.91, 0.58, 0.66])

In [42]:
#Checking how much predicted value is correct,compared to a actual value
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0.52 0.49]
 [0.79 0.66]
 [0.93 0.93]
 [0.86 0.83]
 [0.67 0.7 ]
 [0.73 0.84]
 [0.8  0.77]
 [0.97 0.95]
 [0.51 0.51]
 [0.53 0.54]
 [1.01 0.96]
 [0.94 0.94]
 [0.81 0.87]
 [0.77 0.73]
 [0.67 0.71]
 [0.93 0.94]
 [0.81 0.84]
 [0.75 0.8 ]
 [0.65 0.68]
 [0.51 0.47]
 [0.57 0.64]
 [0.79 0.78]
 [0.72 0.77]
 [0.61 0.64]
 [0.73 0.68]
 [0.65 0.62]
 [0.64 0.72]
 [0.62 0.73]
 [0.63 0.71]
 [0.79 0.74]
 [0.8  0.77]
 [0.89 0.9 ]
 [0.58 0.64]
 [0.92 0.94]
 [0.72 0.77]
 [0.67 0.73]
 [0.73 0.81]
 [0.53 0.57]
 [0.83 0.85]
 [0.79 0.79]
 [0.62 0.54]
 [0.6  0.65]
 [0.75 0.75]
 [0.63 0.68]
 [0.63 0.64]
 [0.68 0.56]
 [0.73 0.71]
 [0.81 0.82]
 [0.65 0.53]
 [0.71 0.8 ]
 [0.89 0.86]
 [0.65 0.64]
 [0.88 0.89]
 [0.67 0.7 ]
 [0.92 0.9 ]
 [0.73 0.52]
 [0.58 0.58]
 [0.65 0.75]
 [0.76 0.73]
 [0.79 0.8 ]
 [0.79 0.8 ]
 [0.52 0.45]
 [0.77 0.69]
 [0.89 0.92]
 [0.7  0.63]
 [0.97 0.97]
 [0.83 0.89]
 [0.55 0.42]
 [0.78 0.76]
 [0.74 0.71]
 [0.82 0.79]
 [0.82 0.85]
 [0.65 0.53]
 [0.8  0.79]
 [0.8  0.84]
 [0.89 0.9 ]
 [0.73 0.66]
 [0.8  0.8 ]
 [0.72 0.78]
 [0.84 0.86]
 [0.95 0.94]
 [0.93 0.94]
 [0.89 0.93]
 [0.74 0.75]
 [0.76 0.79]
 [0.77 0.76]
 [0.71 0.74]
 [0.62 0.64]
 [0.81 0.83]
 [0.95 0.91]
 [0.67 0.74]
 [0.39 0.46]
 [0.8  0.8 ]
 [0.95 0.93]
 [0.87 0.85]
 [0.74 0.78]
 [0.85 0.87]
 [0.64 0.71]
 [0.83 0.82]
 [0.58 0.58]
 [0.61 0.54]
 [0.64 0.73]
 [0.66 0.69]
 [0.66 0.68]
 [0.65 0.66]
 [0.7  0.72]
 [0.65 0.61]
 [0.63 0.5 ]
 [0.75 0.74]
 [0.62 0.63]
 [0.92 0.91]
 [0.76 0.72]
 [0.79 0.74]
 [0.67 0.71]
 [0.88 0.89]
 [0.79 0.85]
 [0.98 0.95]
 [0.91 0.93]
 [0.58 0.52]
 [0.66 0.72]]

In [43]:
#Mean absolute error
from sklearn.metrics import mean_absolute_error
mae=mean_absolute_error(y_pred,y_test)
mae

0.04091666666666667